global using System;
global using System.Collections.Generic;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.Globalization;
global using System.IO;
global using System.Linq;
global using System.Net.Http;
global using System.Reflection;
global using System.Text;
global using System.Threading.Tasks;
global using CsvHelper.Configuration;
global using MeteoSwissApi.Models;
global using MeteoSwissApi.Models.Converters;
global using MeteoSwissApi.Resources.Strings;
global using MeteoSwissApi.Serialization;
global using MeteoSwissApi.Utils;
global using Microsoft.Extensions.Logging;
global using UnitsNet;
global using UnitsNet.Units;
global using JsonConverter = System.Text.Json.Serialization.JsonConverterAttribute;
global using JsonIgnore = System.Text.Json.Serialization.JsonIgnoreAttribute;
global using JsonProperty = System.Text.Json.Serialization.JsonPropertyNameAttribute;
