//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeteoSwissApi.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SlfStationTypes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SlfStationTypes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MeteoSwissApi.Resources.Strings.SlfStationTypes", typeof(SlfStationTypes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snowdrift sensor.
        /// </summary>
        internal static string FLOWCAPT {
            get {
                return ResourceManager.GetString("FLOWCAPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain station.
        /// </summary>
        internal static string PLUVIO {
            get {
                return ResourceManager.GetString("PLUVIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow station.
        /// </summary>
        internal static string SNOW_FLAT {
            get {
                return ResourceManager.GetString("SNOW_FLAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow station.
        /// </summary>
        internal static string SNOW_SLOPE {
            get {
                return ResourceManager.GetString("SNOW_SLOPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special measurement station.
        /// </summary>
        internal static string SPECIAL {
            get {
                return ResourceManager.GetString("SPECIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind station.
        /// </summary>
        internal static string WIND {
            get {
                return ResourceManager.GetString("WIND", resourceCulture);
            }
        }
    }
}
