//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeteoSwissApi.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WarnTypes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WarnTypes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MeteoSwissApi.Resources.Strings.WarnTypes", typeof(WarnTypes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avalanches.
        /// </summary>
        internal static string Avalanches {
            get {
                return ResourceManager.GetString("Avalanches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earthquakes.
        /// </summary>
        internal static string Earthquakes {
            get {
                return ResourceManager.GetString("Earthquakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floods.
        /// </summary>
        internal static string Floods {
            get {
                return ResourceManager.GetString("Floods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forest fire.
        /// </summary>
        internal static string ForestFire {
            get {
                return ResourceManager.GetString("ForestFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frost.
        /// </summary>
        internal static string Frost {
            get {
                return ResourceManager.GetString("Frost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat.
        /// </summary>
        internal static string Heat {
            get {
                return ResourceManager.GetString("Heat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass movements.
        /// </summary>
        internal static string MassMovements {
            get {
                return ResourceManager.GetString("MassMovements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain.
        /// </summary>
        internal static string Rain {
            get {
                return ResourceManager.GetString("Rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slippery roads.
        /// </summary>
        internal static string SlipperyRoads {
            get {
                return ResourceManager.GetString("SlipperyRoads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow.
        /// </summary>
        internal static string Snow {
            get {
                return ResourceManager.GetString("Snow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderstorms.
        /// </summary>
        internal static string Thunderstorms {
            get {
                return ResourceManager.GetString("Thunderstorms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind.
        /// </summary>
        internal static string Wind {
            get {
                return ResourceManager.GetString("Wind", resourceCulture);
            }
        }
    }
}
